[package]
name = "pong"
version = "0.1.0"
authors = ["arnau <diazarnau0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty-hex = "0.2.1"
once_cell = "1.5.2"
cargo-expand = "1.0.1"